spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yasin007/config-repo
          username: yasinapple@163.com
          password: yy6831062

server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
